import type { Genre } from "@kove-advanced/creation-schema";

export const PRE_BAKED_GENRES: readonly Genre[] = [
  {
    id: "highlight-reel",
    name: "Highlight Reel",
    description:
      "Fast-paced compilation of the best moments. High energy, quick cuts, rhythm-driven editing.",
    rules: {
      pacing: "fast",
      transitionPreference: ["hardCut", "whipPan", "flash"],
      effectPalette: ["brightness", "contrast", "saturation"],
      textStyle: "minimal",
      cutStyle: "hard",
      colorMood: "vibrant",
      musicRole: "rhythmic",
    },
    pacing: "fast",
    cutsPerMinuteTarget: [24, 45],
    effectPalette: ["brightness", "contrast", "saturation", "zoom-punch"],
    transitionPalette: ["hardCut", "whipPan", "flash"],
    musicMoodHints: ["energetic", "rhythmic", "modern"],
  },
  {
    id: "documentary",
    name: "Documentary",
    description:
      "Slow, deliberate pacing with context-rich text overlays. Lets the footage breathe.",
    rules: {
      pacing: "slow",
      transitionPreference: ["crossfade", "dipToBlack"],
      effectPalette: ["color-balance", "vignette"],
      textStyle: "moderate",
      cutStyle: "soft",
      colorMood: "neutral",
      musicRole: "background",
    },
    pacing: "slow",
    cutsPerMinuteTarget: [4, 14],
    effectPalette: ["color-balance", "vignette"],
    transitionPalette: ["crossfade", "dipToBlack"],
    musicMoodHints: ["documentary", "restrained", "atmospheric"],
  },
  {
    id: "vlog",
    name: "Vlog",
    description:
      "Conversational, personal feel. Mixed pacing with natural transitions.",
    rules: {
      pacing: "medium",
      transitionPreference: ["crossfade", "wipe", "slide"],
      effectPalette: ["brightness", "warmth"],
      textStyle: "moderate",
      cutStyle: "mixed",
      colorMood: "warm",
      musicRole: "background",
    },
    pacing: "medium",
    cutsPerMinuteTarget: [8, 20],
    effectPalette: ["brightness", "warmth"],
    transitionPalette: ["crossfade", "wipe", "slide"],
    musicMoodHints: ["warm", "casual", "ambient"],
  },
  {
    id: "tutorial",
    name: "Tutorial",
    description:
      "Step-by-step clarity. Text-heavy with deliberate pacing on key moments.",
    rules: {
      pacing: "medium",
      transitionPreference: ["crossfade", "dipToBlack"],
      effectPalette: ["brightness", "contrast"],
      textStyle: "heavy",
      cutStyle: "soft",
      colorMood: "neutral",
      musicRole: "background",
    },
    pacing: "medium",
    cutsPerMinuteTarget: [10, 24],
    effectPalette: ["brightness", "contrast"],
    transitionPalette: ["crossfade", "dipToBlack"],
    musicMoodHints: ["focused", "light", "low volume"],
  },
  {
    id: "music-video",
    name: "Music Video",
    description:
      "Rhythm-synced cuts with heavy visual effects. The music drives the edit.",
    rules: {
      pacing: "fast",
      transitionPreference: ["hardCut", "glitch", "flash", "whipPan"],
      effectPalette: [
        "brightness",
        "contrast",
        "saturation",
        "hue-saturation",
        "chromatic-aberration",
        "motion-blur",
      ],
      textStyle: "minimal",
      cutStyle: "hard",
      colorMood: "vibrant",
      musicRole: "featured",
    },
    pacing: "fast",
    cutsPerMinuteTarget: [18, 42],
    effectPalette: ["brightness", "contrast", "saturation", "chromatic-aberration", "motion-blur"],
    transitionPalette: ["hardCut", "glitch", "flash", "whipPan"],
    musicMoodHints: ["rhythmic", "featured", "high energy"],
  },
  {
    id: "corporate",
    name: "Corporate",
    description:
      "Clean, professional. Minimal effects, clear messaging, polished feel.",
    rules: {
      pacing: "slow",
      transitionPreference: ["crossfade", "dipToWhite"],
      effectPalette: ["brightness", "contrast"],
      textStyle: "moderate",
      cutStyle: "soft",
      colorMood: "cool",
      musicRole: "background",
    },
    pacing: "slow",
    cutsPerMinuteTarget: [4, 12],
    effectPalette: ["brightness", "contrast"],
    transitionPalette: ["crossfade", "dipToWhite"],
    musicMoodHints: ["polished", "corporate", "subtle"],
  },
  {
    id: "social-reel",
    name: "Social Reel",
    description:
      "Short-form, punchy, caption-heavy. Optimized for vertical mobile viewing.",
    rules: {
      pacing: "fast",
      transitionPreference: ["hardCut", "zoom", "slide"],
      effectPalette: ["brightness", "saturation", "contrast"],
      textStyle: "heavy",
      cutStyle: "hard",
      colorMood: "vibrant",
      musicRole: "rhythmic",
    },
    pacing: "fast",
    cutsPerMinuteTarget: [20, 40],
    effectPalette: ["brightness", "saturation", "contrast", "zoom-punch"],
    transitionPalette: ["hardCut", "zoom", "slide"],
    musicMoodHints: ["upbeat", "rhythmic", "modern"],
  },
  {
    id: "same-person-compare",
    name: "Same Person / Comparison",
    description: "A fast split-screen comparison format with consistent captions and two sources visible at once.",
    layoutHint: "split-compare",
    pacing: "fast",
    cutsPerMinuteTarget: [18, 36],
    captionTemplate: { fontFamily: "Arial", fontSize: 48, fontWeight: 700, color: "#ffffff", position: { x: 0.5, y: 0.86 }, align: "center", animation: "text-reveal-up" },
    effectPalette: ["brightness", "contrast", "saturation", "zoom-punch"],
    transitionPalette: ["hardCut", "match-cut"],
    musicMoodHints: ["playful", "punchy", "social"],
    rules: { pacing: "fast", transitionPreference: ["hardCut", "match-cut"], effectPalette: ["brightness", "contrast", "saturation"], textStyle: "heavy", cutStyle: "hard", colorMood: "vibrant", musicRole: "rhythmic" },
  },
  {
    id: "kill-montage",
    name: "Gaming Kill Montage",
    description: "Very fast gameplay montage with impact effects and short hit-marker SFX cues.",
    pacing: "fast",
    cutsPerMinuteTarget: [30, 60],
    effectPalette: ["zoom-punch", "shake", "chromatic-aberration"],
    transitionPalette: ["hardCut"],
    musicMoodHints: ["aggressive", "electronic", "impact-driven"],
    rules: { pacing: "fast", transitionPreference: ["hardCut"], effectPalette: ["zoom-punch", "shake", "chromatic-aberration"], textStyle: "minimal", cutStyle: "hard", colorMood: "vibrant", musicRole: "rhythmic" },
  },
  {
    id: "cinematic-trailer",
    name: "Cinematic Trailer",
    description: "A restrained opening that accelerates into a dramatic climax with title cards and audio swells.",
    pacing: "slow",
    cutsPerMinuteTarget: [8, 24],
    effectPalette: ["vignette", "color-balance", "motion-blur"],
    transitionPalette: ["crossfade", "dipToBlack", "hardCut"],
    musicMoodHints: ["orchestral", "ominous", "rising tension"],
    rules: { pacing: "slow", transitionPreference: ["crossfade", "dipToBlack", "hardCut"], effectPalette: ["vignette", "color-balance", "motion-blur"], textStyle: "minimal", cutStyle: "mixed", colorMood: "cool", musicRole: "featured" },
  },
  {
    id: "tutorial-howto",
    name: "Tutorial / How-To",
    description: "Clear instructional pacing with lower-thirds, step callouts, and consistent explanatory captions.",
    layoutHint: "sequential",
    pacing: "medium",
    cutsPerMinuteTarget: [10, 24],
    captionTemplate: { fontSize: 36, color: "#ffffff", backgroundColor: "#111111", backgroundPadding: 12, backgroundRadius: 6, position: { x: 0.08, y: 0.86 }, align: "left" },
    effectPalette: ["brightness", "contrast"],
    transitionPalette: ["crossfade", "hardCut"],
    musicMoodHints: ["light", "focused", "low volume"],
    rules: { pacing: "medium", transitionPreference: ["crossfade", "hardCut"], effectPalette: ["brightness", "contrast"], textStyle: "heavy", cutStyle: "soft", colorMood: "neutral", musicRole: "background" },
  },
  {
    id: "before-after",
    name: "Before / After Transformation",
    description: "A measured transformation reveal using held frames and a clean split comparison.",
    layoutHint: "split-compare",
    pacing: "slow",
    cutsPerMinuteTarget: [4, 14],
    effectPalette: ["brightness", "contrast", "saturation"],
    transitionPalette: ["match-cut", "crossfade"],
    musicMoodHints: ["anticipatory", "uplifting", "minimal"],
    rules: { pacing: "slow", transitionPreference: ["match-cut", "crossfade"], effectPalette: ["brightness", "contrast", "saturation"], textStyle: "moderate", cutStyle: "soft", colorMood: "neutral", musicRole: "background" },
  },
  {
    id: "day-in-the-life",
    name: "Day in the Life / Vlog",
    description: "Personal, natural pacing with timestamp captions and an ambient music bed.",
    pacing: "medium",
    cutsPerMinuteTarget: [8, 20],
    effectPalette: ["brightness", "warmth"],
    transitionPalette: ["crossfade", "hardCut", "slide"],
    musicMoodHints: ["warm", "ambient", "casual"],
    rules: { pacing: "medium", transitionPreference: ["crossfade", "hardCut", "slide"], effectPalette: ["brightness", "warmth"], textStyle: "moderate", cutStyle: "mixed", colorMood: "warm", musicRole: "background" },
  },
  {
    id: "product-demo",
    name: "Product Demo",
    description: "Feature-led product presentation with callouts, clean cuts, and optional reaction PIP.",
    layoutHint: "pip-reaction",
    pacing: "medium",
    cutsPerMinuteTarget: [8, 20],
    captionTemplate: { fontSize: 40, fontWeight: 600, color: "#ffffff", position: { x: 0.08, y: 0.14 }, align: "left" },
    effectPalette: ["brightness", "contrast", "sharpen"],
    transitionPalette: ["hardCut", "crossfade", "slide"],
    musicMoodHints: ["clean", "confident", "modern"],
    rules: { pacing: "medium", transitionPreference: ["hardCut", "crossfade", "slide"], effectPalette: ["brightness", "contrast"], textStyle: "moderate", cutStyle: "mixed", colorMood: "cool", musicRole: "background" },
  },
  {
    id: "podcast-clip",
    name: "Podcast Clip",
    description: "Dialogue-forward edit with readable captions, speaker identification, and restrained visual motion.",
    pacing: "slow",
    cutsPerMinuteTarget: [4, 12],
    captionTemplate: { fontSize: 42, fontWeight: 700, color: "#ffffff", position: { x: 0.5, y: 0.78 }, align: "center", animation: "text-reveal-up" },
    effectPalette: ["contrast", "color-balance"],
    transitionPalette: ["hardCut", "crossfade"],
    musicMoodHints: ["none", "subtle", "dialogue-first"],
    rules: { pacing: "slow", transitionPreference: ["hardCut", "crossfade"], effectPalette: ["contrast", "color-balance"], textStyle: "heavy", cutStyle: "soft", colorMood: "neutral", musicRole: "background" },
  },
  {
    id: "listicle-countdown",
    name: "Countdown / Listicle",
    description: "Fast numbered beats with one clear title card or caption treatment per item.",
    pacing: "fast",
    cutsPerMinuteTarget: [18, 36],
    effectPalette: ["zoom-punch", "brightness", "saturation"],
    transitionPalette: ["hardCut", "slide", "whipPan"],
    musicMoodHints: ["upbeat", "countdown", "playful"],
    rules: { pacing: "fast", transitionPreference: ["hardCut", "slide", "whipPan"], effectPalette: ["zoom-punch", "brightness", "saturation"], textStyle: "heavy", cutStyle: "hard", colorMood: "vibrant", musicRole: "rhythmic" },
  },
  {
    id: "meme-compilation",
    name: "Meme Compilation",
    description: "Very fast comedic compilation using hard cuts and minimal transition decoration.",
    pacing: "fast",
    cutsPerMinuteTarget: [30, 75],
    effectPalette: ["zoom-punch", "shake", "brightness"],
    transitionPalette: ["hardCut"],
    musicMoodHints: ["comedic", "chaotic", "viral"],
    rules: { pacing: "fast", transitionPreference: ["hardCut"], effectPalette: ["zoom-punch", "shake", "brightness"], textStyle: "heavy", cutStyle: "hard", colorMood: "vibrant", musicRole: "rhythmic" },
  },
  {
    id: "sports-highlight",
    name: "Sports Highlight Reel",
    description: "Energetic sports edit with slow motion on key moments, score overlays, and impact sound cues.",
    pacing: "fast",
    cutsPerMinuteTarget: [20, 45],
    effectPalette: ["zoom-punch", "motion-blur", "contrast", "saturation"],
    transitionPalette: ["hardCut", "whipPan", "flash"],
    musicMoodHints: ["anthemic", "stadium", "high energy"],
    rules: { pacing: "fast", transitionPreference: ["hardCut", "whipPan", "flash"], effectPalette: ["zoom-punch", "motion-blur", "contrast", "saturation"], textStyle: "moderate", cutStyle: "hard", colorMood: "vibrant", musicRole: "rhythmic" },
  },
  {
    id: "glow-up-reveal",
    name: "Glow-Up / Prank Reveal",
    description: "A suspenseful setup that resolves into a visual reveal, often using a split comparison or reveal transition.",
    layoutHint: "split-compare",
    pacing: "medium",
    cutsPerMinuteTarget: [10, 24],
    effectPalette: ["brightness", "saturation", "zoom-punch"],
    transitionPalette: ["match-cut", "flash", "crossfade"],
    musicMoodHints: ["suspenseful", "playful", "reveal"],
    rules: { pacing: "medium", transitionPreference: ["match-cut", "flash", "crossfade"], effectPalette: ["brightness", "saturation", "zoom-punch"], textStyle: "moderate", cutStyle: "mixed", colorMood: "vibrant", musicRole: "featured" },
  },
];

export function getGenreById(id: string): Genre | undefined {
  return PRE_BAKED_GENRES.find((g) => g.id === id);
}

export function listGenreIds(): readonly string[] {
  return PRE_BAKED_GENRES.map((g) => g.id);
}
