import { CAPABILITY_MANIFEST } from "@kove-advanced/core/capabilities/manifest";
import { toCapabilityDoc, toolDefs } from "./registry";

/**
 * Renders the agent capability reference (tool catalog + capability manifest)
 * as Markdown. The source of truth is the tool registry, so this regenerates
 * docs/AGENT-CAPABILITIES.md without hand-maintenance.
 */
export function generateCapabilityMarkdown(): string {
  const count = toolDefs().length;
  return [
    "<!-- AUTO-GENERATED by @kove-advanced/agent generateCapabilityMarkdown(). Do not edit by hand. -->",
    "",
    "# Kove Advanced Agent — Capability Reference",
    "",
    `The agent exposes **${count} tools** spanning read/observe, project, track, clip, transform, effect, color, speed, audio, subtitle, keyframe, transition, marker, text and graphics domains — plus \`execute_action\` and \`batch_actions\` escape hatches for any capability without a dedicated tool.`,
    "",
    "## Tools",
    "",
    toCapabilityDoc()
      .trim()
      .replace(/^#\s+Kove Advanced Agent Tools\n?/, ""),
    "",
    "## Capability manifest (enums + parameter ranges)",
    "",
    "```json",
    JSON.stringify(CAPABILITY_MANIFEST, null, 2),
    "```",
    "",
  ].join("\n");
}
